name: Test

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Rollup requires Node.js >=18
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Build package
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: ./dist/ # build output
          retention-days: 1 # keep the artifact for 1 day

  test:
    name: Test LTS
    needs: build
    strategy:
      fail-fast: false # doesn't stop on first failure
      matrix:
        os: [ubuntu-latest]
        node-version: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: built-package
          path: ./dist/

      - name: Install dependencies (without rebuilding)
        run: npm install --ignore-scripts

      - name: Run tests
        run: npx run test:coverage
        env:
          NODE_OPTIONS: --unhandled-rejections=strict

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: webdiscus/flaget
